USE [master]
GO
/****** Object:  Database [BookStoreDatabase]    Script Date: 11/8/2021 7:47:59 PM ******/
CREATE DATABASE [BookStoreDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookStoreDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BookStoreDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookStoreDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BookStoreDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [BookStoreDatabase] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookStoreDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BookStoreDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BookStoreDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BookStoreDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BookStoreDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BookStoreDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET RECOVERY FULL 
GO
ALTER DATABASE [BookStoreDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [BookStoreDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BookStoreDatabase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BookStoreDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BookStoreDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BookStoreDatabase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BookStoreDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BookStoreDatabase', N'ON'
GO
ALTER DATABASE [BookStoreDatabase] SET QUERY_STORE = OFF
GO
USE [BookStoreDatabase]
GO
/****** Object:  Table [dbo].[Assigned_to]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Assigned_to](
	[ISBN] [int] NOT NULL,
	[Category_Code] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ISBN] ASC,
	[Category_Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Author_of_the_books]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Author_of_the_books](
	[AuthorID] [int] NOT NULL,
	[First_Name] [varchar](40) NOT NULL,
	[Last_Name] [varchar](40) NOT NULL,
	[Gender] [bit] NULL,
	[Date_of_Birth] [date] NULL,
	[ContactID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[AuthorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Book_Categories]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book_Categories](
	[Category_Code] [int] NOT NULL,
	[Category_Desc] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Category_Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Books]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Books](
	[ISBN] [int] NOT NULL,
	[Title] [varchar](100) NOT NULL,
	[Publication_Date] [date] NOT NULL,
	[Price] [decimal](9, 2) NOT NULL,
	[User_Reviews] [varchar](100) NULL,
	[SupplierID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ISBN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAddress]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAddress](
	[Address] [varchar](100) NOT NULL,
	[ContactID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Address] ASC,
	[ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CMail]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CMail](
	[Email] [varchar](40) NOT NULL,
	[ContactID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Email] ASC,
	[ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CNumber]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CNumber](
	[Phone_Number] [int] NOT NULL,
	[ContactID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Phone_Number] ASC,
	[ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contact_Details]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contact_Details](
	[ContactID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[CustomerID] [int] NOT NULL,
	[First_Name] [varchar](40) NOT NULL,
	[Last_Name] [varchar](40) NOT NULL,
	[ContactID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Order_Items]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order_Items](
	[Item_Number] [int] NOT NULL,
	[Item_Price] [decimal](9, 2) NOT NULL,
	[ISBN] [int] NULL,
	[OrderID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Item_Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrderID] [int] NOT NULL,
	[Order_Date] [date] NOT NULL,
	[Order_Value] [decimal](9, 2) NULL,
	[CustomerID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Supplier]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Supplier](
	[SupplierID] [int] NOT NULL,
	[Supplier_Name] [varchar](40) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SupplierID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Supplier_Rep]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Supplier_Rep](
	[First_Name] [varchar](40) NOT NULL,
	[Last_Name] [varchar](40) NOT NULL,
	[Work_Number] [int] NULL,
	[Cell_Number] [int] NULL,
	[Email] [varchar](40) NULL,
	[SupplierID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[First_Name] ASC,
	[Last_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Written_by]    Script Date: 11/8/2021 7:47:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Written_by](
	[ISBN] [int] NOT NULL,
	[AuthorID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ISBN] ASC,
	[AuthorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Assigned_to]  WITH CHECK ADD FOREIGN KEY([Category_Code])
REFERENCES [dbo].[Book_Categories] ([Category_Code])
GO
ALTER TABLE [dbo].[Assigned_to]  WITH CHECK ADD FOREIGN KEY([ISBN])
REFERENCES [dbo].[Books] ([ISBN])
GO
ALTER TABLE [dbo].[Author_of_the_books]  WITH CHECK ADD FOREIGN KEY([ContactID])
REFERENCES [dbo].[Contact_Details] ([ContactID])
GO
ALTER TABLE [dbo].[Books]  WITH CHECK ADD FOREIGN KEY([SupplierID])
REFERENCES [dbo].[Supplier] ([SupplierID])
GO
ALTER TABLE [dbo].[CAddress]  WITH CHECK ADD FOREIGN KEY([ContactID])
REFERENCES [dbo].[Contact_Details] ([ContactID])
GO
ALTER TABLE [dbo].[CMail]  WITH CHECK ADD FOREIGN KEY([ContactID])
REFERENCES [dbo].[Contact_Details] ([ContactID])
GO
ALTER TABLE [dbo].[CNumber]  WITH CHECK ADD FOREIGN KEY([ContactID])
REFERENCES [dbo].[Contact_Details] ([ContactID])
GO
ALTER TABLE [dbo].[Customer]  WITH CHECK ADD FOREIGN KEY([ContactID])
REFERENCES [dbo].[Contact_Details] ([ContactID])
GO
ALTER TABLE [dbo].[Order_Items]  WITH CHECK ADD FOREIGN KEY([OrderID])
REFERENCES [dbo].[Orders] ([OrderID])
GO
ALTER TABLE [dbo].[Order_Items]  WITH CHECK ADD FOREIGN KEY([ISBN])
REFERENCES [dbo].[Books] ([ISBN])
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD FOREIGN KEY([CustomerID])
REFERENCES [dbo].[Customer] ([CustomerID])
GO
ALTER TABLE [dbo].[Supplier_Rep]  WITH CHECK ADD FOREIGN KEY([SupplierID])
REFERENCES [dbo].[Supplier] ([SupplierID])
GO
ALTER TABLE [dbo].[Written_by]  WITH CHECK ADD FOREIGN KEY([AuthorID])
REFERENCES [dbo].[Author_of_the_books] ([AuthorID])
GO
ALTER TABLE [dbo].[Written_by]  WITH CHECK ADD FOREIGN KEY([ISBN])
REFERENCES [dbo].[Books] ([ISBN])
GO
USE [master]
GO
ALTER DATABASE [BookStoreDatabase] SET  READ_WRITE 
GO
